services:
  - type: web
    name: hammernet
    env: python
    buildCommand: "./build.sh"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: hammernet-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: ALLOWED_ORIGINS
        value: "http://localhost:4321,http://localhost:8000,https://hammernet.onrender.com"
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "8000"

databases:
  - name: hammernet-db
    databaseName: hammernet
    user: hammernet_user